# YML file for setting up a virtual environment capable of running GeoFabrics

name: geofabrics_CI
channels:
  - conda-forge
dependencies:
  - python=3.12
  - python-pdal==3.4.5
  - pip
  - pip:
    - rioxarray==0.17.0
    - geoapis==0.3.4
    - osmpythontools==0.3.5
    - distributed==2024.8.2
    - scipy==1.14.1
