# YML file for setting up a virtual environment capable of running GeoFabrics

name: geofabrics_CI
channels:
  - conda-forge
dependencies:
  - rioxarray >= 0.15.1
  - geoapis>= 0.3.2
  - osmpythontools >= 0.3.5
  - python-pdal >= 3.3.0
  - dask >= 2023.6.0
  - distributed >= 2023.6.0
  - netcdf4
  - libgdal-hdf5
